server:
  port: 8086
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    localdatasource:
      url: jdbc:sqlite:E:/develop/SQLite/parcelx_fabric.db
      username:
      password:
      driver-class-name: org.sqlite.JDBC

scheduled:
  # 每天4点抽卡次数清空
  cleanJob: 0 0 4 */1 * ?
  # 每天晚8点日报统计
  countJob: 0 0 20 */1 * ?
  # 每天早8点播报干员庆生
  birthdayJob: 0 0 8 */1 * ?
  # 每3分钟监听一次B站动态
  biliJob: 0 */3 * * * ?
  # 每3分钟监听一次微博动态
  sinaJob: 0 */3 * * * ?
  # 每5分钟检查一次数据更新
  updateJob: 0 */5 * * * ?
  # 每周日晚5点剿灭提醒
  exterminateJob: 0 0 17 ? * SUN
userConfig:
  #登录的机器人qq
  loginQq:
  #OPQ框架部署的IP
  OPQUrl: localhost
baiduConfig:
  APP_ID:
  API_KEY:
  SECRET_KEY: